spring.application.name=sms

# H2 DataSource
spring.datasource.url=jdbc:h2:mem:smsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (view DB in browser at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
